name: Test

on: push

jobs:
    build:
        strategy:
            matrix:
                go-version: [~1.13, ^1]
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        env:
            GO111MODULE: "on"
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.16

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...
